version: "3.8"

services:
  acc_service:
    build: backend/accounting-service
    ports:
      - "5003:5003"
  loan_service:
    build: backend/loan-service
    ports:
    - "5002:5002"
  user_service:
    build: backend/user-service
    ports:
    - "5001:5001"
  dec_engine:
    build: third-party/decision-engine
    ports:
    - "3005:3005"
  xero_api:
    build: third-party/xero-api
    ports:
    - "3006:3006"
  myob_api:
    build: third-party/myob-api
    ports:
    - "3007:3007"
  app:
    build: app
    ports:
    - "3000:3000"
